# Docker Compose for local development.
version: "2.1"
services:
  frontend:
    container_name: quartz-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    command: "yarn start --host"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/build"
  contracts:
    container_name: quartz-node
    build:
      context: contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - "./contracts:/build"
  backend:
    container_name: quartz-backend
    build:
      context: backend
      dockerfile: Dockerfile
    command: "yarn start"
    ports:
      - "8080:8080"
    volumes:
      - "./backend:/build"
