# Docker Compose for local development.
version: "2.1"
services:
  dashboard:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    command: "yarn start --host"
    ports:
      - "3000:3000"
  # contracts:
  #   container_name: contracts
  #   build:
  #     context: contracts
  #     dockerfile: Dockerfile
  #   command: "yarn start"
  #   ports:
  #     - "4000:8000"
  # backend:
  #   container_name: backend
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   command: "yarn start"
  #   ports:
  #     - "4000:8000"
